// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgqueries

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID          uuid.UUID
	Username    string
	Password    string
	Nickname    string
	PrivateCode string
	CreatedAt   sql.NullTime
}
