// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgqueries

import (
	"database/sql"

	"github.com/google/uuid"
)

type Client struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ClientKey uuid.UUID
	RevokedAt sql.NullTime
	CreatedAt sql.NullTime
}

type Message struct {
	ID         uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.NullUUID
	RoomID     uuid.NullUUID
	ContentEnc string
	CreatedAt  sql.NullTime
}

type Room struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Code      string
	Password  string
	CreatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	Nickname  string
	Role      string
	CreatedAt sql.NullTime
}
