# 1. Build stage
FROM golang:1.24.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN go build -o Asistolog ./cmd/project

# 2. Production image
FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/Asistolog .
COPY --from=builder /app/config ./config
COPY --from=builder /app/env ./env
COPY --from=builder /app/internal/adapters/postgres/migrations ./internal/adapters/postgres/migrations

EXPOSE 8080

CMD ["./Asistolog"]
