# 1. Build stage
FROM golang:1.24.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN go build -o ./build/server ./cmd/server

# 2. Production image
FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/deployment/ ./deployment
COPY --from=builder /app/build/server .
COPY --from=builder /app/configs ./configs
COPY --from=builder /app/env ./env
COPY --from=builder /app/internal/adapters/postgres/migrations ./internal/adapters/postgres/migrations
COPY --from=builder /app/certs/ ./certs

EXPOSE 8080

CMD ["./server"]
