client_id: d8c799a6-2b45-4c94-8c45-63774d124569 # Our custom id for each flash.
server_name: slam
server_host: localhost
server_port: 6666
tls_cert_path: "./certs/server.crt"
timeout_seconds: 1
reconnect_retry: 3
