# Unique identifier for each client device (e.g., USB flash drive)
client_key: 8539a6ce-4d10-45bc-a83c-e8f9463833e0 # Our custom id for each flash.

# Server connection details including name, host, and port
server_name: slam
server_host: localhost
server_port: 6666
tls_cert_path: "./certs/example/server.crt"

# Network and connection settings for client
timeout_seconds: 1
reconnect_retry: 3
