# Application specific settings including mode and migration path
app:
  migration_path: "/app/internal/adapters/postgres/migrations"

# Server configuration including host, port, and TLS certificate paths
server:
  external_host:
  host: 192.168.1.27
  port: 6666
  tls_cert_path: "./certs/real/server.crt"
  tls_key_path: "./certs/real/server.key"
