app:
  mode: development
  migration_path: "/app/internal/adapters/postgres/migrations"

server:
  host: 0.0.0.0
  port: 6666
  require_auth: true
  message_lifetime_hours: 24
  max_clients: 100
  tls_cert_path: "./certs/server.crt"
  tls_key_path: "./certs/server.key"

JWT:
  issuer: SLAM
  secret: u549QD5weh9A04n
