# Application specific settings including mode and migration path
app:
  mode: development
  migration_path: "/app/internal/adapters/postgres/migrations"

# Server configuration including host, port, and TLS certificate paths
server:
  host: 0.0.0.0
  port: 6666
  tls_cert_path: "./certs/example/server.crt"
  tls_key_path: "./certs/example/server.key"

# JWT configuration for token issuer and secret key (change for production)
jwt:
  issuer: SLAM
  secret: u549QD5weh9A04n
