host: 0.0.0.0
port: 6666
require_auth: true
message_lifetime_hours: 24
log_level: info
max_clients: 100
tls_cert_path: "./certs/server.crt"
tls_key_path: "./certs/server.key"

app_env: development
migration_path: "/app/internal/adapters/postgres/migrations"
