# Application specific settings including mode and migration path
app:
  mode: dev
  migration_path: "/app/internal/adapters/postgres/migrations"

# Server configuration including host, port, and TLS certificate paths
server:
  host: localhost
  port: 6666
  tls_cert_path: "./certs/real/server.crt"
  tls_key_path: "./certs/real/server.key"
